#!/bin/sh
set -eu

if [ -z "${OPENAI_BASE_URL:-}" ]; then
  echo "OPENAI_BASE_URL is required" >&2
  exit 1
fi

exec "${QM_CODEX_REAL_BIN:-/app/node_modules/.bin/codex}" \
  -c 'model_provider="glm"' \
  -c 'model_providers.glm.name="GLM"' \
  -c "model_providers.glm.base_url=\"${OPENAI_BASE_URL}\"" \
  -c 'model_providers.glm.env_key="OPENAI_API_KEY"' \
  -c 'model_providers.glm.wire_api="responses"' \
  -c 'model_providers.glm.supports_websockets=false' \
  "$@"
